# -*- coding: utf-8 -*-
"""Encoder_Decoder_Attention_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13j1o0L074Yj40RrQVsYpLVDQ3_FtHkmg
"""

# Install required libraries
!pip install nltk rouge-score datasets

# Core libraries
import numpy as np
import tensorflow as tf
import random
import time
import os

# NLP libraries
import nltk
from nltk.translate.bleu_score import sentence_bleu, corpus_bleu, SmoothingFunction

# Visualization
import matplotlib.pyplot as plt

# Dataset (for Part 3)
from datasets import load_dataset

# Download tokenizer
nltk.download('punkt')

# Fix randomness for reproducibility
np.random.seed(42)
tf.random.set_seed(42)
random.seed(42)

print("TensorFlow version:", tf.__version__)

gpus = tf.config.list_physical_devices('GPU')
print("GPU available:", gpus)

if gpus:
    print("GPU is enabled 🚀")
else:
    print("Running on CPU ⚠️")

print("All libraries installed and imported successfully ✅")

# Small English → German dataset (toy dataset)

english_sentences = [
    "i love you",
    "hello world",
    "how are you",
    "good morning",
    "thank you",
    "i am happy",
    "he is good",
    "she is sad",
    "they are here",
    "i am learning"
]

german_sentences = [
    "ich liebe dich",
    "hallo welt",
    "wie geht es dir",
    "guten morgen",
    "danke schoen",
    "ich bin gluecklich",
    "er ist gut",
    "sie ist traurig",
    "sie sind hier",
    "ich lerne"
]

print("Dataset loaded successfully ✅")
print("Total sentence pairs:", len(english_sentences))

# Display sample pairs

for i in range(5):
    print(f"{i+1}. EN: {english_sentences[i]}  →  DE: {german_sentences[i]}")

# Simple lowercase cleaning

def clean_text(sentence):
    return sentence.lower().strip()

english_sentences = [clean_text(s) for s in english_sentences]
german_sentences = [clean_text(s) for s in german_sentences]

print("Text cleaned successfully ✅")

# Analyze sentence lengths

max_len_en = max(len(s.split()) for s in english_sentences)
max_len_de = max(len(s.split()) for s in german_sentences)

print("Max English length:", max_len_en)
print("Max German length:", max_len_de)

# Special tokens
PAD = 0
SOS = 1
EOS = 2
UNK = 3

class Vocabulary:
    def __init__(self):
        self.word2idx = {
            "<pad>": PAD,
            "<sos>": SOS,
            "<eos>": EOS,
            "<unk>": UNK
        }
        self.idx2word = {
            PAD: "<pad>",
            SOS: "<sos>",
            EOS: "<eos>",
            UNK: "<unk>"
        }
        self.count = 4  # starting index

    def add_sentence(self, sentence):
        for word in sentence.split():
            self.add_word(word)

    def add_word(self, word):
        if word not in self.word2idx:
            self.word2idx[word] = self.count
            self.idx2word[self.count] = word
            self.count += 1

    def __len__(self):
        return self.count

# Create vocab objects
src_vocab = Vocabulary()
tgt_vocab = Vocabulary()

# Add sentences to vocab
for sentence in english_sentences:
    src_vocab.add_sentence(sentence)

for sentence in german_sentences:
    tgt_vocab.add_sentence(sentence)

print("Source Vocabulary Size:", len(src_vocab))
print("Target Vocabulary Size:", len(tgt_vocab))

# Show some word mappings

print("\nSample word mappings (English):")
for word, idx in list(src_vocab.word2idx.items())[:10]:
    print(f"{word} → {idx}")

print("\nSample word mappings (German):")
for word, idx in list(tgt_vocab.word2idx.items())[:10]:
    print(f"{word} → {idx}")

# Convert sentence to indices

def encode_sentence(sentence, vocab):
    return [vocab.word2idx.get(word, UNK) for word in sentence.split()]

# Example
print("Sample Encoding:")
print("Sentence:", english_sentences[0])
print("Encoded:", encode_sentence(english_sentences[0], src_vocab))

# Add <sos> and <eos>

def add_tokens(sequence):
    return [SOS] + sequence + [EOS]

# Example
sample = encode_sentence(english_sentences[0], src_vocab)
print("With tokens:", add_tokens(sample))

# Pad sequences to fixed length

def pad_sequence(seq, max_len):
    return seq + [PAD] * (max_len - len(seq))

MAX_LEN = 10

encoder_inputs = []
decoder_inputs = []
decoder_targets = []

for src, tgt in zip(english_sentences, german_sentences):

    # Encode
    src_seq = encode_sentence(src, src_vocab)
    tgt_seq = encode_sentence(tgt, tgt_vocab)

    # Add tokens
    src_seq = add_tokens(src_seq)
    tgt_seq = add_tokens(tgt_seq)

    # Prepare decoder input and target
    dec_input = tgt_seq[:-1]   # remove last
    dec_target = tgt_seq[1:]   # remove first

    # Pad
    encoder_inputs.append(pad_sequence(src_seq, MAX_LEN))
    decoder_inputs.append(pad_sequence(dec_input, MAX_LEN))
    decoder_targets.append(pad_sequence(dec_target, MAX_LEN))

# Convert to numpy
import numpy as np

encoder_inputs = np.array(encoder_inputs)
decoder_inputs = np.array(decoder_inputs)
decoder_targets = np.array(decoder_targets)

print("Shapes:")
print("Encoder:", encoder_inputs.shape)
print("Decoder Input:", decoder_inputs.shape)
print("Decoder Target:", decoder_targets.shape)

# Show one sample

print("Original:", english_sentences[0])
print("Encoded:", encoder_inputs[0])

print("\nDecoder Input:", decoder_inputs[0])
print("Decoder Target:", decoder_targets[0])

class Encoder(tf.keras.layers.Layer):
    def __init__(self, vocab_size, embedding_dim=64, hidden_dim=128):
        super().__init__()

        # Embedding layer: converts word indices → dense vectors
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)

        # Bidirectional LSTM
        self.bilstm = tf.keras.layers.Bidirectional(
            tf.keras.layers.LSTM(hidden_dim,
                                 return_sequences=True,
                                 return_state=True)
        )

        # Dense layer to reduce dimension (important!)
        self.fc = tf.keras.layers.Dense(hidden_dim)

    def call(self, x):
        # x shape: (batch_size, seq_len)

        x = self.embedding(x)
        # shape: (batch, seq_len, embedding_dim)

        outputs, forward_h, forward_c, backward_h, backward_c = self.bilstm(x)

        # Concatenate forward & backward states
        hidden = tf.concat([forward_h, backward_h], axis=-1)
        cell = tf.concat([forward_c, backward_c], axis=-1)

        # Reduce dimension to match decoder
        hidden = self.fc(hidden)
        cell = self.fc(cell)

        return outputs, hidden, cell

# Create encoder instance
encoder = Encoder(vocab_size=len(src_vocab.word2idx))

print("Encoder initialized successfully ✅")

# Test with sample input

sample_input = encoder_inputs[:2]  # batch of 2

outputs, hidden, cell = encoder(sample_input)

print("Encoder Output Shape:", outputs.shape)
print("Hidden Shape:", hidden.shape)
print("Cell Shape:", cell.shape)

class LuongAttention(tf.keras.layers.Layer):
    def __init__(self, hidden_dim):
        super().__init__()

        # Linear layer to transform encoder outputs
        self.W = tf.keras.layers.Dense(hidden_dim)

    def call(self, decoder_hidden, encoder_outputs):
        """
        decoder_hidden: (batch, hidden_dim)
        encoder_outputs: (batch, seq_len, hidden_dim)
        """

        # Expand decoder hidden → (batch, 1, hidden)
        decoder_hidden = tf.expand_dims(decoder_hidden, 1)

        # Compute score
        score = tf.reduce_sum(
            self.W(encoder_outputs) * decoder_hidden,
            axis=2
        )  # (batch, seq_len)

        # Convert to probabilities
        attention_weights = tf.nn.softmax(score, axis=1)

        # Compute context vector
        context_vector = tf.reduce_sum(
            encoder_outputs * tf.expand_dims(attention_weights, 2),
            axis=1
        )  # (batch, hidden_dim)

        return context_vector, attention_weights

attention = LuongAttention(hidden_dim=128)

print("Attention initialized ✅")

# Use encoder output from previous section

context, weights = attention(hidden, outputs)

print("Context Shape:", context.shape)
print("Attention Weights Shape:", weights.shape)

print("Sum of weights (should be ~1):")
print(tf.reduce_sum(weights[0]))

class Decoder(tf.keras.layers.Layer):
    def __init__(self, vocab_size, embedding_dim=64, hidden_dim=128):
        super().__init__()

        # Embedding layer
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)

        # LSTM Cell (step-by-step decoding)
        self.lstm = tf.keras.layers.LSTMCell(hidden_dim)

        # Attention layer
        self.attention = LuongAttention(hidden_dim)

        # Final output layer
        self.fc = tf.keras.layers.Dense(vocab_size)

    def call(self, decoder_inputs, hidden, cell, encoder_outputs):
        """
        decoder_inputs: (batch, seq_len)
        hidden, cell: (batch, hidden)
        encoder_outputs: (batch, seq_len, hidden)
        """

        outputs = []

        # Loop over each time step
        for t in range(decoder_inputs.shape[1]):

            # Get word at time step t
            x = self.embedding(decoder_inputs[:, t])   # (batch, embedding)

            # LSTM step
            hidden, [hidden, cell] = self.lstm(x, [hidden, cell])

            # Apply attention
            context_vector, attention_weights = self.attention(hidden, encoder_outputs)

            # Combine hidden + context
            combined = tf.concat([hidden, context_vector], axis=-1)

            # Predict next word
            output = self.fc(combined)

            outputs.append(output)

        # Stack outputs → (batch, seq_len, vocab_size)
        outputs = tf.stack(outputs, axis=1)

        return outputs

decoder = Decoder(vocab_size=len(tgt_vocab.word2idx))

print("Decoder initialized successfully ✅")

# Test with encoder output

sample_input = encoder_inputs[:2]

enc_outputs, hidden, cell = encoder(sample_input)

dec_out = decoder(decoder_inputs[:2], hidden, cell, enc_outputs)

print("Decoder Output Shape:", dec_out.shape)

class Seq2Seq(tf.keras.Model):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def call(self, encoder_inputs, decoder_inputs):
        """
        encoder_inputs: (batch, seq_len)
        decoder_inputs: (batch, seq_len)
        """

        # Step 1: Pass through encoder
        encoder_outputs, hidden, cell = self.encoder(encoder_inputs)

        # Step 2: Pass through decoder (with attention)
        decoder_outputs = self.decoder(
            decoder_inputs,
            hidden,
            cell,
            encoder_outputs
        )

        return decoder_outputs

model = Seq2Seq(encoder, decoder)

print("Full Model Created Successfully ✅")

# Test forward pass

sample_enc = encoder_inputs[:2]
sample_dec = decoder_inputs[:2]

outputs = model(sample_enc, sample_dec)

print("Model Output Shape:", outputs.shape)

class Seq2Seq_NoAttention(tf.keras.Model):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def call(self, encoder_inputs, decoder_inputs):
        encoder_outputs, hidden, cell = self.encoder(encoder_inputs)

        # ❌ No attention used
        outputs = []

        for t in range(decoder_inputs.shape[1]):
            x = decoder.embedding(decoder_inputs[:, t])
            hidden, [hidden, cell] = decoder.lstm(x, [hidden, cell])
            out = decoder.fc(hidden)
            outputs.append(out)

        return tf.stack(outputs, axis=1)

# Loss function
loss_function = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

@tf.function
def train_step(enc_inp, dec_inp, dec_tar):

    with tf.GradientTape() as tape:
        predictions = model(enc_inp, dec_inp)

        loss = loss_function(dec_tar, predictions)

    gradients = tape.gradient(loss, model.trainable_variables)

    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    return loss

EPOCHS = 50

loss_history = []

start_time = time.time()

for epoch in range(EPOCHS):

    loss = train_step(encoder_inputs, decoder_inputs, decoder_targets)

    loss_history.append(loss.numpy())

    if epoch % 10 == 0:
        print(f"Epoch {epoch} | Loss: {loss.numpy():.4f}")

end_time = time.time()

training_time = end_time - start_time

print("\nTraining Completed ✅")
print("Total Training Time:", training_time, "seconds")

import matplotlib.pyplot as plt

plt.plot(loss_history, label="Training Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Loss vs Epochs")
plt.legend()
plt.show()

class Decoder_NoAttention(tf.keras.layers.Layer):
    def __init__(self, vocab_size, embedding_dim=64, hidden_dim=128):
        super().__init__()

        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.lstm = tf.keras.layers.LSTMCell(hidden_dim)

        # ⚠️ IMPORTANT: input = hidden only (NOT hidden+context)
        self.fc = tf.keras.layers.Dense(vocab_size)

    def call(self, decoder_inputs, hidden, cell):
        outputs = []

        for t in range(decoder_inputs.shape[1]):
            x = self.embedding(decoder_inputs[:, t])

            hidden, [hidden, cell] = self.lstm(x, [hidden, cell])

            # ONLY hidden (correct)
            out = self.fc(hidden)

            outputs.append(out)

        return tf.stack(outputs, axis=1)

class Seq2Seq_NoAttention(tf.keras.Model):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def call(self, encoder_inputs, decoder_inputs):
        encoder_outputs, hidden, cell = self.encoder(encoder_inputs)

        # ⚠️ No attention → ignore encoder_outputs
        outputs = self.decoder(decoder_inputs, hidden, cell)

        return outputs

decoder_no_attn = Decoder_NoAttention(vocab_size=len(tgt_vocab.word2idx))

model_no_attn = Seq2Seq_NoAttention(encoder, decoder_no_attn)

optimizer2 = tf.keras.optimizers.Adam()

loss_no_attn = []

for epoch in range(EPOCHS):

    with tf.GradientTape() as tape:
        preds = model_no_attn(encoder_inputs, decoder_inputs)
        loss = loss_function(decoder_targets, preds)

    grads = tape.gradient(loss, model_no_attn.trainable_variables)
    optimizer2.apply_gradients(zip(grads, model_no_attn.trainable_variables))

    loss_no_attn.append(loss.numpy())

    if epoch % 10 == 0:
        print(f"[No Attn] Epoch {epoch} | Loss: {loss.numpy():.4f}")

def predict_sentence(model, sentence):

    # Encode input sentence
    seq = encode_sentence(sentence, src_vocab)
    seq = [SOS] + seq + [EOS]

    # Pad input
    seq = seq + [PAD] * (10 - len(seq))
    seq = np.array([seq])

    # Encoder forward pass
    encoder_outputs, hidden, cell = model.encoder(seq)

    # Start with <sos>
    dec_input = np.array([[SOS]])

    result = []

    for _ in range(10):

        preds = model.decoder(dec_input, hidden, cell, encoder_outputs)

        # Get predicted word
        pred_id = tf.argmax(preds[0, 0]).numpy()

        if pred_id == EOS:
            break

        result.append(tgt_vocab.idx2word.get(pred_id, "<unk>"))

        # Next input
        dec_input = np.array([[pred_id]])

    return " ".join(result)

print("Input:", "i love you")
print("Prediction:", predict_sentence(model, "i love you"))

test_sentences = [
    "i love you",
    "good morning",
    "thank you"
]

for sent in test_sentences:
    print("\nInput:", sent)
    print("Prediction:", predict_sentence(model, sent))

def calculate_bleu(reference, prediction):
    smoothie = SmoothingFunction().method4
    return sentence_bleu([reference.split()], prediction.split(), smoothing_function=smoothie)

bleu_scores = []

for src, tgt in zip(english_sentences, german_sentences):
    pred = predict_sentence(model, src)

    score = calculate_bleu(tgt, pred)
    bleu_scores.append(score)

    print(f"\nInput: {src}")
    print(f"Target: {tgt}")
    print(f"Predicted: {pred}")
    print(f"BLEU: {score:.4f}")

avg_bleu = np.mean(bleu_scores)

print("\nAverage BLEU Score:", avg_bleu)

def predict_sentence_attn(model, sentence):

    seq = encode_sentence(sentence, src_vocab)
    seq = [SOS] + seq + [EOS]
    seq = seq + [PAD] * (10 - len(seq))
    seq = np.array([seq])

    encoder_outputs, hidden, cell = model.encoder(seq)

    dec_input = np.array([[SOS]])
    result = []

    for _ in range(10):
        preds = model.decoder(dec_input, hidden, cell, encoder_outputs)

        pred_id = tf.argmax(preds[0, 0]).numpy()

        if pred_id == EOS:
            break

        result.append(tgt_vocab.idx2word.get(pred_id, "<unk>"))
        dec_input = np.array([[pred_id]])

    return " ".join(result)

def predict_sentence_no_attn(model, sentence):

    seq = encode_sentence(sentence, src_vocab)
    seq = [SOS] + seq + [EOS]
    seq = seq + [PAD] * (10 - len(seq))
    seq = np.array([seq])

    # Encoder
    _, hidden, cell = model.encoder(seq)

    dec_input = np.array([[SOS]])
    result = []

    for _ in range(10):

        preds = model.decoder(dec_input, hidden, cell)

        pred_id = tf.argmax(preds[0, 0]).numpy()

        if pred_id == EOS:
            break

        result.append(tgt_vocab.idx2word.get(pred_id, "<unk>"))

        dec_input = np.array([[pred_id]])

    return " ".join(result)

bleu_scores = []

for src, tgt in zip(english_sentences, german_sentences):
    pred = predict_sentence_attn(model, src)

    score = calculate_bleu(tgt, pred)
    bleu_scores.append(score)

print("BLEU (Attention):", np.mean(bleu_scores))

bleu_no_attn = []

for src, tgt in zip(english_sentences, german_sentences):
    pred = predict_sentence_no_attn(model_no_attn, src)

    score = calculate_bleu(tgt, pred)
    bleu_no_attn.append(score)

print("BLEU (No Attention):", np.mean(bleu_no_attn))

