# -*- coding: utf-8 -*-
"""XAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdwUX5ih7JST-QjkCEAFa6Al3SyKVB0E

Name: Aarya Malghe
PRN: 2023011000061
"""

# Install XAI libraries
!pip install shap lime

# Basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Explainable AI
import shap
from lime.lime_tabular import LimeTabularExplainer

# For better visualization
sns.set(style="whitegrid")

"""#Part 1: Dataset Selection and Preprocessing"""

# Load Titanic dataset from online source
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

# Display first 5 rows
df.head()

# Dataset info
print("\nDataset Info:")
print(df.info())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Reload original dataset
df_raw = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

plt.figure()
sns.heatmap(df_raw.isnull(), cbar=False)
plt.title("Missing Values BEFORE Preprocessing")
plt.show()

df = df.drop(['PassengerId'], axis=1)

print("\nColumns after dropping unnecessary ones:")
print(df.columns)

# Fill missing values
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Verify missing values are removed
print("\nMissing values after handling:")
print(df.isnull().sum())

# Convert categorical columns into numerical
df = pd.get_dummies(df, drop_first=True)

print("\nDataset after encoding:")
print(df.head())

X = df.drop('Survived', axis=1)
y = df['Survived']

print("\nFeature columns:")
print(X.columns)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("\nTrain/Test Split:")
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure()
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap")
plt.show()

plt.figure()
sns.countplot(x='Survived', data=df)
plt.title("Survival Distribution")
plt.show()

"""#PART 2: MODEL IMPLEMENTATION"""

# Machine Learning libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create Random Forest model
# n_estimators = number of trees
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train model on training data
model.fit(X_train, y_train)

print("Model training completed successfully!")

# Predict on test data
y_pred = model.predict(X_test)

# Show first 10 predictions
print("First 10 Predictions:", y_pred[:10])
print("Actual Values:", y_test.values[:10])

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot
plt.figure()
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Extract feature importance
importances = model.feature_importances_
features = X.columns

# Create DataFrame
feat_df = pd.DataFrame({
    'Feature': features,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

# Plot
plt.figure()
sns.barplot(x='Importance', y='Feature', data=feat_df)
plt.title("Feature Importance (Model Interpretation)")
plt.show()

plt.figure()
sns.countplot(x=y_pred)
plt.title("Predicted Survival Distribution")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.show()

"""#Part 3: Applying Explainable AI Techniques"""

# Get feature importance from Random Forest
importances = model.feature_importances_
features = X.columns

# Create DataFrame
feat_df = pd.DataFrame({
    'Feature': features,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

# Plot feature importance
plt.figure()
sns.barplot(x='Importance', y='Feature', data=feat_df)
plt.title("Global Explanation: Feature Importance")
plt.show()

!pip install shap

import shap

# Ensure numeric (you already did this)
X_train = X_train.astype(float)
X_test = X_test.astype(float)

# Use TreeExplainer (better for Random Forest)
explainer = shap.TreeExplainer(model)

# Disable additivity check
shap_values = explainer.shap_values(X_test, check_additivity=False)

# Plot
shap.summary_plot(shap_values[:, :, 1], X_test)

explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(X_test, check_additivity=False)

# Global plot
shap.summary_plot(shap_values[:, :, 1], X_test)

shap.dependence_plot("Fare", shap_values[:, :, 1], X_test)

!pip install lime

from lime.lime_tabular import LimeTabularExplainer
import numpy as np

# Create LIME explainer
lime_explainer = LimeTabularExplainer(
    training_data=np.array(X_train),
    feature_names=X.columns,
    class_names=['Not Survived', 'Survived'],
    mode='classification'
)

# Select one instance
i = 5

# Explain prediction
exp = lime_explainer.explain_instance(
    X_test.iloc[i],
    model.predict_proba
)

# Show explanation
exp.show_in_notebook(show_table=True)

shap.initjs()

shap.plots.force(
    explainer.expected_value[1],     # base value
    shap_values[:, :, 1][0],         # SHAP values for one sample
    X_test.iloc[0]                   # feature values
)

"""#PART 4: VISUALIZATION & ANALYSIS"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Feature Correlation Heatmap")
plt.show()

plt.figure()
sns.barplot(x='Sex', y='Survived', data=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"))
plt.title("Survival Rate by Gender")
plt.show()

plt.figure()
sns.barplot(x='Pclass', y='Survived', data=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"))
plt.title("Survival Rate by Passenger Class")
plt.show()

plt.figure()
sns.histplot(data=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"),
             x='Age', hue='Survived', bins=30, kde=True)
plt.title("Age Distribution by Survival")
plt.show()

from sklearn.inspection import permutation_importance

result = permutation_importance(model, X_test, y_test, n_repeats=10, random_state=42)

perm_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': result.importances_mean
}).sort_values(by='Importance', ascending=False)

plt.figure()
sns.barplot(x='Importance', y='Feature', data=perm_df)
plt.title("Permutation Importance (Global XAI)")
plt.show()

y_prob = model.predict_proba(X_test)[:,1]

plt.figure()
sns.histplot(y_prob, bins=20, kde=True)
plt.title("Prediction Probability Distribution")
plt.xlabel("Survival Probability")
plt.show()

