# -*- coding: utf-8 -*-
"""DL Lab 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-arubMwvmFY_16VI1G1BRXRqPlpkMUJ

Google Colab Lab Assignment
Course Name: DEEP LEARNING



Student Name: Aarya Malghe

Student ID: 202301100061

Date of Submission: 09-04-26

Group Members:  Harsh Kumar,
              Ayush Chandekar,
               Sanket Rath

Github Link: https://github.com/aaarya2809/DL_Assignments/tree/main/Assignment_4
"""

# === 1. Setup & Imports (Improved) ===

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import warnings
warnings.filterwarnings('ignore')

# NLP Libraries
import nltk

# Download required resources (cleaner approach)
nltk_packages = [
    'punkt', 'stopwords', 'wordnet',
    'averaged_perceptron_tagger', 'punkt_tab' # Added 'punkt_tab'
]

for pkg in nltk_packages:
    nltk.download(pkg, quiet=True)

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

# ML Libraries
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("✅ All imports loaded successfully")

# === 2. Load Dataset (Improved with Error Handling) ===

def load_dataset(url):
    try:
        df = pd.read_csv(url, sep='\t', header=None, names=['label', 'message'])
        print("✅ Dataset loaded successfully")
        return df
    except Exception as e:
        print("❌ Error loading dataset:", e)
        return None


url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
df = load_dataset(url)

# Basic Info
print("\n--- Dataset Summary ---")
print(f"Total messages : {len(df)}")
print(f"Spam messages  : {df[df['label'] == 'spam'].shape[0]}")
print(f"Ham messages   : {df[df['label'] == 'ham'].shape[0]}")

# === 3. Feature Engineering ===

df['char_count'] = df['message'].apply(len)
df['word_count'] = df['message'].apply(lambda x: len(x.split()))
df['digit_count'] = df['message'].apply(lambda x: sum(c.isdigit() for c in x))
df['upper_count'] = df['message'].apply(lambda x: sum(c.isupper() for c in x))

print("\n✅ Feature Engineering Done")
print(df.head())

# === 4. Enhanced Exploratory Data Analysis ===

print("Dataset Shape:", df.shape)

# --- Label Distribution ---
print("\nLabel distribution:")
print(df['label'].value_counts(normalize=True) * 100)

# --- Advanced Feature Engineering ---
df['msg_length'] = df['message'].apply(len)
df['word_count'] = df['message'].apply(lambda x: len(x.split()))
df['avg_word_length'] = df['msg_length'] / (df['word_count'] + 1)
df['digit_count'] = df['message'].apply(lambda x: sum(c.isdigit() for c in x))
df['special_char_count'] = df['message'].apply(lambda x: sum(not c.isalnum() for c in x))

# --- Statistical Summary ---
print("\n📊 Statistical Summary:")
print(df.groupby('label')[['msg_length', 'word_count', 'digit_count']].mean().round(2))

# --- Top Words in Spam vs Ham ---
from collections import Counter

def get_top_words(text_series, n=10):
    all_words = " ".join(text_series).split()
    return Counter(all_words).most_common(n)

print("\n🔥 Top words in SPAM:")
print(get_top_words(df[df['label']=='spam']['message']))

print("\n🔥 Top words in HAM:")
print(get_top_words(df[df['label']=='ham']['message']))

# === Visualization Section ===

plt.figure(figsize=(14,8))

# 1. Label Distribution
plt.subplot(2,2,1)
sns.countplot(x='label', data=df)
plt.title("Spam vs Ham Count")

# 2. Message Length Distribution
plt.subplot(2,2,2)
sns.histplot(data=df, x='msg_length', hue='label', bins=40)
plt.title("Message Length Distribution")

# 3. Word Count Boxplot
plt.subplot(2,2,3)
sns.boxplot(x='label', y='word_count', data=df)
plt.title("Word Count Comparison")

# 4. Correlation Heatmap (NEW 🔥)
plt.subplot(2,2,4)
corr = df[['msg_length','word_count','digit_count','special_char_count']].corr()
sns.heatmap(corr, annot=True)
plt.title("Feature Correlation")

plt.tight_layout()
plt.savefig('advanced_eda.png', dpi=120)
plt.show()

"""#NLP Preprocessing From Scratch"""

# === Advanced Manual NLP Preprocessing (From Scratch) ===

# --- Step 1: Smarter Tokenizer ---
def manual_tokenize(text):
    text = text.lower()

    # replace punctuation with space
    for ch in string.punctuation:
        text = text.replace(ch, ' ')

    tokens = []
    for word in text.split():
        # remove tokens with only numbers or very short tokens
        if word.isdigit():
            continue
        if len(word) <= 2:
            continue
        tokens.append(word)

    return tokens

# --- Step 2: Improved Stopwords ---
# Added more realistic stopwords (important for NLP quality)

MANUAL_STOPWORDS = set([
    'i','me','my','myself','we','our','ours','you','your','yours',
    'he','him','his','she','her','it','its','they','them','their',
    'what','which','who','this','that','these','those',
    'am','is','are','was','were','be','been','being',
    'have','has','had','do','does','did',
    'will','would','should','can','could','may','might',
    'a','an','the','and','but','if','or','because','as',
    'of','at','by','for','with','about','to','from','in','on','up',
    'so','than','too','very','just','now','only'
])

def manual_remove_stopwords(tokens):
    return [word for word in tokens if word not in MANUAL_STOPWORDS]

# --- Step 3: Smarter Stemming (Improved Rules) ---

def manual_stem(word):
    suffixes = ['ization','ational','fulness','ousness','iveness',
                'tion','ing','edly','edly','ed','ly','er','es','s']

    for suffix in suffixes:
        if word.endswith(suffix) and len(word) - len(suffix) >= 3:
            return word[:-len(suffix)]

    return word


def manual_stem_tokens(tokens):
    return [manual_stem(word) for word in tokens]

# --- Step 4: NEW Feature Extraction (🔥 BIG UPGRADE) ---

def extract_manual_features(text):
    return {
        "has_number": int(any(c.isdigit() for c in text)),
        "has_uppercase": int(any(c.isupper() for c in text)),
        "has_exclamation": int("!" in text),
        "has_url": int("http" in text or "www" in text)
    }

# --- Step 5: Full Pipeline ---

def manual_preprocess(text):
    tokens = manual_tokenize(text)
    tokens = manual_remove_stopwords(tokens)
    tokens = manual_stem_tokens(tokens)
    return ' '.join(tokens)

# --- Step 6: Testing (Better Output Display) ---

test_messages = [
    "Congratulations! You've won a FREE iPhone. Click here to claim your prize!",
    "Hey, are we still meeting for lunch tomorrow at noon?",
    "URGENT: Your bank account has been compromised. Verify your details NOW!"
]

print("🚀 Advanced Manual NLP Pipeline")
print("=" * 60)

for msg in test_messages:
    processed = manual_preprocess(msg)
    features = extract_manual_features(msg)

    print(f"\nOriginal  : {msg}")
    print(f"Processed : {processed}")
    print(f"Features  : {features}")

# --- Step 7: Apply to Dataset ---

print("\nApplying advanced manual preprocessing...")

df['manual_processed'] = df['message'].apply(manual_preprocess)

# Extract additional manual features
feature_df = df['message'].apply(lambda x: pd.Series(extract_manual_features(x)))

df = pd.concat([df, feature_df], axis=1)

print("✅ Done")

print("\nSample Output:")
print(df[['message', 'manual_processed', 'has_number', 'has_exclamation']].head(3))

"""#NLP Preprocessing Using Libraries"""

# === Advanced NLP Preprocessing using NLTK ===

from nltk import pos_tag
from nltk.corpus import wordnet

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

# --- POS Tag Conversion (VERY IMPORTANT UPGRADE) ---
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

# --- Advanced Preprocessing Pipeline ---

def advanced_library_preprocess(text, use_stemming=False):

    # Step 1: Lowercase
    text = text.lower()

    # Step 2: Remove punctuation & numbers
    text = re.sub(r'[^a-z\s]', '', text)

    # Step 3: Tokenization
    tokens = word_tokenize(text)

    # Step 4: Stopword removal
    tokens = [word for word in tokens if word not in stop_words and len(word) > 2]

    # Step 5: POS tagging (NEW 🔥)
    pos_tags = pos_tag(tokens)

    # Step 6: Lemmatization using POS
    lemmatized = [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in pos_tags
    ]

    # Step 7: Optional stemming
    if use_stemming:
        lemmatized = [stemmer.stem(word) for word in lemmatized]

    return " ".join(lemmatized)

# --- Extra Feature Extraction (Spam Indicators 🔥) ---

def extract_advanced_features(text):
    return {
        "length": len(text),
        "num_digits": sum(c.isdigit() for c in text),
        "num_caps": sum(c.isupper() for c in text),
        "num_special": sum(not c.isalnum() for c in text),
        "has_link": int("http" in text or "www" in text),
        "has_money": int("£" in text or "$" in text)
    }

# === Robust NLTK Downloads ===

nltk_packages = [
    'punkt',
    'stopwords',
    'wordnet',
    'averaged_perceptron_tagger',
    'averaged_perceptron_tagger_eng'   # important fix
]

for pkg in nltk_packages:
    try:
        nltk.download(pkg, quiet=True)
    except:
        print(f"Skipping {pkg}")

# --- Apply to Dataset (Optimized) ---

print("Applying advanced NLP preprocessing...")

df['processed_advanced'] = df['message'].apply(advanced_library_preprocess)

# Add features
feature_df = df['message'].apply(lambda x: pd.Series(extract_advanced_features(x)))
df = pd.concat([df, feature_df], axis=1)

print("✅ Done")

# --- Improved Comparison Output ---

print("\n🔍 Comparison (Manual vs Advanced NLP)")
print("=" * 70)

for i in range(3):
    print(f"\nOriginal   : {df['message'][i][:80]}")
    print(f"Manual     : {df['manual_processed'][i][:80]}")
    print(f"NLTK Adv   : {df['processed_advanced'][i][:80]}")

"""#POS Tagging"""

# === Improved Scratch POS Tagger ===

def improved_scratch_pos_tagger(tokens):
    tagged = []

    for i, word in enumerate(tokens):
        if word in ['is','are','was','were','be','been','am','have','has','do','does']:
            tag = 'VB'
        elif word.endswith('ing'):
            tag = 'VBG'
        elif word.endswith('ed'):
            tag = 'VBD'
        elif word.endswith('ly'):
            tag = 'RB'
        elif word.endswith(('ous','ful','able','ive')):
            tag = 'JJ'
        elif word.endswith(('tion','ness','ment')):
            tag = 'NN'
        elif word.isdigit():
            tag = 'CD'
        elif len(word) <= 2:
            tag = 'IN'  # preposition/determiner approx
        else:
            tag = 'NN'

        tagged.append((word, tag))

    return tagged

from nltk import pos_tag
from nltk.tokenize import word_tokenize
from collections import Counter

def get_pos_distribution(text_series):
    pos_counts = Counter()

    for text in text_series:
        tokens = word_tokenize(text)
        tags = pos_tag(tokens)

        for _, tag in tags:
            pos_counts[tag[:2]] += 1   # group like NN, VB, JJ

    return pos_counts


# Separate spam and ham
spam_texts = df[df['label']=='spam']['message']
ham_texts  = df[df['label']=='ham']['message']

spam_pos_dist = get_pos_distribution(spam_texts[:200])  # limit for speed
ham_pos_dist  = get_pos_distribution(ham_texts[:200])

print("Spam POS Distribution:", spam_pos_dist)
print("Ham POS Distribution :", ham_pos_dist)

# === POS Comparison Plot ===

common_tags = ['NN','VB','JJ','RB']

spam_values = [spam_pos_dist.get(tag,0) for tag in common_tags]
ham_values  = [ham_pos_dist.get(tag,0) for tag in common_tags]

x = range(len(common_tags))

plt.figure(figsize=(8,5))

plt.bar(x, spam_values, width=0.4, label='Spam')
plt.bar([i+0.4 for i in x], ham_values, width=0.4, label='Ham')

plt.xticks([i+0.2 for i in x], common_tags)
plt.title("POS Tag Distribution: Spam vs Ham")
plt.xlabel("POS Tags")
plt.ylabel("Frequency")
plt.legend()

plt.show()

print("\n📊 POS Comparison Table")
print("-"*40)
print(f"{'POS':<10}{'Spam':<10}{'Ham':<10}")

for tag in common_tags:
    print(f"{tag:<10}{spam_pos_dist.get(tag,0):<10}{ham_pos_dist.get(tag,0):<10}")

"""# Named Entity Recognition (NER)"""

# === Improved Scratch NER ===

def improved_scratch_ner(tokens):
    entities = []

    org_keywords    = ['nokia','vodafone','google','facebook','amazon','paypal']
    person_titles   = ['mr','mrs','miss','dr','sir']
    place_keywords  = ['london','uk','usa','india','california']

    i = 0
    while i < len(tokens):
        word = tokens[i].lower()

        # MONEY (more flexible)
        if any(sym in word for sym in ['£','$','rs']):
            entities.append((tokens[i], 'MONEY'))

        # PHONE / LARGE NUMBER
        elif word.isdigit() and len(word) >= 5:
            entities.append((tokens[i], 'NUMBER'))

        # DATE (extended)
        elif word in ['jan','feb','march','april','may','june','july',
                      'aug','sep','oct','nov','dec']:
            entities.append((tokens[i], 'DATE'))

        # PERSON (title + name)
        elif word in person_titles and i+1 < len(tokens):
            entities.append((tokens[i] + ' ' + tokens[i+1], 'PERSON'))
            i += 1

        # ORG
        elif word in org_keywords:
            entities.append((tokens[i], 'ORG'))

        # PLACE
        elif word in place_keywords:
            entities.append((tokens[i], 'GPE'))

        i += 1

    return entities

import spacy

# Load model (run once)
nlp = spacy.load("en_core_web_sm")

def spacy_ner(text):
    doc = nlp(text)
    return [(ent.text, ent.label_) for ent in doc.ents]

from collections import Counter

def get_entity_distribution(text_series, ner_function, limit=200):
    entity_counts = Counter()

    # convert to list (important for slicing safely)
    texts = list(text_series)[:limit]

    for text in texts:
        entities = ner_function(text)

        for _, label in entities:
            entity_counts[label] += 1

    return entity_counts

# Separate spam & ham
spam_texts = df[df['label']=='spam']['message']
ham_texts  = df[df['label']=='ham']['message']

# Compute distributions
spam_entities = get_entity_distribution(spam_texts, spacy_ner)
ham_entities  = get_entity_distribution(ham_texts, spacy_ner)

print("Spam Entity Distribution:", spam_entities)
print("Ham Entity Distribution :", ham_entities)

# === Entity Comparison Plot ===

common_entities = list(set(list(spam_entities.keys()) + list(ham_entities.keys())))

spam_vals = [spam_entities.get(ent, 0) for ent in common_entities]
ham_vals  = [ham_entities.get(ent, 0) for ent in common_entities]

x = range(len(common_entities))

plt.figure(figsize=(10,5))

plt.bar(x, spam_vals, width=0.4, label='Spam')
plt.bar([i+0.4 for i in x], ham_vals, width=0.4, label='Ham')

plt.xticks([i+0.2 for i in x], common_entities, rotation=45)
plt.title("NER Distribution: Spam vs Ham")
plt.xlabel("Entity Types")
plt.ylabel("Frequency")
plt.legend()

plt.tight_layout()
plt.show()

print("\n📊 Entity Comparison Table")
print("-"*50)
print(f"{'Entity':<15}{'Spam':<10}{'Ham':<10}")

for ent in common_entities:
    print(f"{ent:<15}{spam_entities.get(ent,0):<10}{ham_entities.get(ent,0):<10}")

"""#Text Vectorization"""

import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def library_preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)

    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]

    lemmatized = [lemmatizer.lemmatize(word) for word in tokens]

    return {
        'lemmatized': ' '.join(lemmatized)
    }

processed = df['message'].apply(library_preprocess)

df['lemmatized_processed'] = processed.apply(lambda x: x['lemmatized'])

print("✅ Preprocessing Done")
print(df[['message', 'lemmatized_processed']].head())

df['label_encoded'] = df['label'].map({'spam': 1, 'ham': 0})

from sklearn.model_selection import train_test_split

X = df['lemmatized_processed']
y = df['label_encoded']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("✅ Train-Test Split Done")

from sklearn.feature_extraction.text import CountVectorizer

print("\n--- CountVectorizer ---")

cv = CountVectorizer(
    max_features=3000,
    ngram_range=(1,2),
    min_df=2
)

X_train_cv = cv.fit_transform(X_train)
X_test_cv  = cv.transform(X_test)

print("Vocabulary size:", len(cv.vocabulary_))
print("Train shape:", X_train_cv.shape)
print("Test shape:", X_test_cv.shape)

word_counts = np.asarray(X_train_cv.sum(axis=0)).flatten()
words = cv.get_feature_names_out()

top_idx = word_counts.argsort()[::-1][:15]

print("\nTop 15 frequent words:")
for i in top_idx:
    print(f"{words[i]:<20} : {word_counts[i]}")

from sklearn.feature_extraction.text import TfidfVectorizer

print("\n--- TF-IDF ---")

tfidf = TfidfVectorizer(
    max_features=3000,
    ngram_range=(1,2),
    min_df=2
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

print("Vocabulary size:", len(tfidf.vocabulary_))
print("Train shape:", X_train_tfidf.shape)
print("Test shape:", X_test_tfidf.shape)

tfidf_scores = np.asarray(X_train_tfidf.mean(axis=0)).flatten()
words = tfidf.get_feature_names_out()

top_idx = tfidf_scores.argsort()[::-1][:15]

print("\nTop 15 TF-IDF words:")
for i in top_idx:
    print(f"{words[i]:<20} : {tfidf_scores[i]:.6f}")

"""#N-Gram"""

# N-Grams - All approaches on spam dataset
# N-grams are sequences of N consecutive words
# bigrams = 2 words, trigrams = 3 words
# helps capture phrases like "free entry", "win cash", "click here"

# -----------------------------------------------------------------------
# APPROACH 1:  (no libraries)
# -----------------------------------------------------------------------

def scratch_ngrams(tokens, n):
    # sliding window of size n over the token list
    ngrams = []
    for i in range(len(tokens) - n + 1):
        ngram = tuple(tokens[i:i+n])
        ngrams.append(ngram)
    return ngrams

spam_example = df[df['label'] == 'spam']['message'].iloc[0]
ham_example  = df[df['label'] == 'ham']['message'].iloc[0]

spam_tokens = manual_tokenize(spam_example)
ham_tokens  = manual_tokenize(ham_example)

print("=== FROM SCRATCH N-Grams ===")
print("\nSpam message:", spam_example[:80])
print("Bigrams  :", scratch_ngrams(spam_tokens, 2)[:5])
print("Trigrams :", scratch_ngrams(spam_tokens, 3)[:5])

print("\nHam message:", ham_example[:80])
print("Bigrams  :", scratch_ngrams(ham_tokens, 2)[:5])
print("Trigrams :", scratch_ngrams(ham_tokens, 3)[:5])

# -----------------------------------------------------------------------
# APPROACH 2: WITH LIBRARY (nltk)
# -----------------------------------------------------------------------
from nltk import ngrams, word_tokenize, FreqDist

print("\n=== WITH LIBRARY (NLTK) N-Grams ===")

# collect all tokens from spam and ham separately
spam_all_tokens = []
ham_all_tokens  = []

for msg in df[df['label'] == 'spam']['message']:
    spam_all_tokens.extend(word_tokenize(str(msg).lower()))

for msg in df[df['label'] == 'ham']['message']:
    ham_all_tokens.extend(word_tokenize(str(msg).lower()))

spam_bigrams  = list(ngrams(spam_all_tokens, 2))
ham_bigrams   = list(ngrams(ham_all_tokens,  2))
spam_trigrams = list(ngrams(spam_all_tokens, 3))
ham_trigrams  = list(ngrams(ham_all_tokens,  3))

spam_bigram_freq  = FreqDist(spam_bigrams)
ham_bigram_freq   = FreqDist(ham_bigrams)
spam_trigram_freq = FreqDist(spam_trigrams)
ham_trigram_freq  = FreqDist(ham_trigrams)

print("\nTop 5 Bigrams in SPAM:")
for gram, count in spam_bigram_freq.most_common(5):
    print(f"  {gram}  ->  {count}")

print("\nTop 5 Bigrams in HAM:")
for gram, count in ham_bigram_freq.most_common(5):
    print(f"  {gram}  ->  {count}")

print("\nTop 5 Trigrams in SPAM:")
for gram, count in spam_trigram_freq.most_common(5):
    print(f"  {gram}  ->  {count}")

print("\nTop 5 Trigrams in HAM:")
for gram, count in ham_trigram_freq.most_common(5):
    print(f"  {gram}  ->  {count}")

# -----------------------------------------------------------------------
# APPROACH 3: EXISTING MODEL (sklearn CountVectorizer with ngram_range)
# -----------------------------------------------------------------------
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

print("\n=== EXISTING MODEL (sklearn) N-Grams ===")

# bigram vectorizer
bigram_vec = CountVectorizer(ngram_range=(2, 2), max_features=10)
bigram_vec.fit(df['message'])

# get top bigrams from spam messages only
spam_text  = df[df['label'] == 'spam']['message']
ham_text   = df[df['label'] == 'ham']['message']

spam_bigram_matrix = bigram_vec.transform(spam_text).toarray().sum(axis=0)
ham_bigram_matrix  = bigram_vec.transform(ham_text).toarray().sum(axis=0)

feature_names = bigram_vec.get_feature_names_out()

print("\nTop Bigrams - Spam vs Ham count (sklearn):")
print(f"{'Bigram':<30} {'Spam count':<15} {'Ham count'}")
print("-" * 55)
for i, bigram in enumerate(feature_names):
    print(f"{bigram:<30} {spam_bigram_matrix[i]:<15} {ham_bigram_matrix[i]}")

from nltk import ngrams, FreqDist
from nltk.tokenize import word_tokenize

print("\n=== NLTK N-Grams (Improved) ===")

def get_top_ngrams(text_series, n=2, top_k=5):
    all_tokens = []

    for msg in text_series:
        tokens = word_tokenize(str(msg).lower())
        all_tokens.extend(tokens)

    n_grams = list(ngrams(all_tokens, n))
    freq = FreqDist(n_grams)

    return freq.most_common(top_k)


# Top n-grams
print("\nTop Bigrams (Spam):", get_top_ngrams(df[df['label']=='spam']['message'], 2))
print("Top Bigrams (Ham) :", get_top_ngrams(df[df['label']=='ham']['message'], 2))

print("\nTop Trigrams (Spam):", get_top_ngrams(df[df['label']=='spam']['message'], 3))
print("Top Trigrams (Ham) :", get_top_ngrams(df[df['label']=='ham']['message'], 3))

from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

print("\n=== Sklearn N-Grams ===")

text_data = df['lemmatized_processed']

vectorizer = CountVectorizer(
    ngram_range=(2,2),
    max_features=20,
    min_df=2
)

X = vectorizer.fit_transform(text_data)
features = vectorizer.get_feature_names_out()

spam_indices = np.where(df['label'] == 'spam')[0]
ham_indices  = np.where(df['label'] == 'ham')[0]

spam_counts = np.asarray(X[spam_indices].sum(axis=0)).flatten()
ham_counts  = np.asarray(X[ham_indices].sum(axis=0)).flatten()

print(f"\n{'Bigram':<30}{'Spam':<10}{'Ham':<10}")
print("-"*50)

for i in range(len(features)):
    print(f"{features[i]:<30}{spam_counts[i]:<10}{ham_counts[i]:<10}")

import matplotlib.pyplot as plt

top_idx = spam_counts.argsort()[::-1][:10]

top_words = [features[i] for i in top_idx]
top_values = [spam_counts[i] for i in top_idx]

plt.figure(figsize=(8,5))
plt.barh(top_words[::-1], top_values[::-1])
plt.title("Top Spam Bigrams")
plt.xlabel("Frequency")
plt.ylabel("Bigrams")
plt.show()

print("\n🔥 Top Spam Trigger Bigrams:")

for i in top_idx:
    print(f"{features[i]} → {spam_counts[i]}")

"""#Word Embeddings"""

!pip install gensim

# === BLOCK 1: Co-occurrence Matrix (From Scratch) ===
# Idea: words that appear together frequently have similar meaning

import numpy as np

def build_cooccurrence(corpus, window=2):
    # Step 1: Build vocabulary (word → index)
    vocab = {}
    idx = 0
    for sentence in corpus:
        for word in sentence:
            if word not in vocab:
                vocab[word] = idx
                idx += 1

    # Step 2: Initialize co-occurrence matrix
    V = len(vocab)
    matrix = np.zeros((V, V))

    # Step 3: Fill matrix using sliding window
    for sentence in corpus:
        for i, word in enumerate(sentence):
            start = max(0, i - window)
            end   = min(len(sentence), i + window + 1)

            for j in range(start, end):
                if i != j:
                    w1 = vocab[word]
                    w2 = vocab[sentence[j]]
                    matrix[w1][w2] += 1

    return vocab, matrix


# Cosine similarity between vectors
def cosine_sim_scratch(v1, v2):
    dot  = np.dot(v1, v2)
    norm = np.linalg.norm(v1) * np.linalg.norm(v2)
    return dot / norm if norm != 0 else 0


# Use small subset (for speed)
subset = df['message'].head(500).tolist()
tokenized = [manual_tokenize(str(msg)) for msg in subset]

print("=== Co-occurrence Embeddings ===")
vocab, cooc_matrix = build_cooccurrence(tokenized)

print("Vocabulary size:", len(vocab))
print("Matrix shape:", cooc_matrix.shape)

# === BLOCK 2: Similarity Check ===

pairs = [('free', 'win'), ('free', 'call'), ('call', 'now'), ('go', 'come')]

print("\nCo-occurrence Similarity:")

for w1, w2 in pairs:
    if w1 in vocab and w2 in vocab:
        sim = cosine_sim_scratch(cooc_matrix[vocab[w1]], cooc_matrix[vocab[w2]])
        print(f"{w1:<10} <-> {w2:<10} : {sim:.4f}")
    else:
        print(f"{w1} or {w2} not found")

# === BLOCK 3: Install & Import Gensim ===

# Run once if not installed
# !pip install gensim

from gensim.models import Word2Vec

# === BLOCK 4: Prepare Tokenized Sentences ===

# Use cleaned/lemmatized text for better results
sentences = [text.split() for text in df['lemmatized_processed']]

print("Sample sentence:", sentences[0])

# === BLOCK 5: Train Word2Vec Model ===

w2v_model = Word2Vec(
    sentences=sentences,
    vector_size=100,   # dimension of vectors
    window=5,          # context size
    min_count=2,       # ignore rare words
    epochs=15,
    sg=1               # skip-gram (better for small data)
)

print("Vocabulary size:", len(w2v_model.wv.key_to_index))
print("Vector size:", w2v_model.vector_size)

# === BLOCK 6: Similar Words ===

keywords = ['free', 'win', 'call', 'txt']

for word in keywords:
    if word in w2v_model.wv:
        print(f"\nWords similar to '{word}':")
        for w, sim in w2v_model.wv.most_similar(word, topn=5):
            print(f"{w:<15} {sim:.4f}")

# === BLOCK 7: Word Pair Similarity ===

pairs = [('free','win'), ('free','call'), ('call','now'), ('go','come')]

print("\nWord2Vec Similarity:")

for w1, w2 in pairs:
    if w1 in w2v_model.wv and w2 in w2v_model.wv:
        sim = w2v_model.wv.similarity(w1, w2)
        print(f"{w1:<10} <-> {w2:<10} : {sim:.4f}")

# === BLOCK 8: Convert Sentences to Vectors ===

import numpy as np

def sentence_vector(sentence):
    words = sentence.split()
    vectors = []

    for word in words:
        if word in w2v_model.wv:
            vectors.append(w2v_model.wv[word])

    if len(vectors) == 0:
        return np.zeros(w2v_model.vector_size)

    return np.mean(vectors, axis=0)


# Apply to dataset
df['w2v_vector'] = df['lemmatized_processed'].apply(sentence_vector)

print("Vector length:", len(df['w2v_vector'][0]))

# === BLOCK 9: Prepare for Machine Learning ===

X_w2v = np.vstack(df['w2v_vector'].values)
y = df['label_encoded']

print("Feature matrix shape:", X_w2v.shape)

"""# Text Similarity"""

# === BLOCK 1: Scratch Cosine Similarity ===
# Convert text → frequency vector → compute cosine similarity

import numpy as np

def scratch_text_vectorize(text, vocab):
    tokens = manual_tokenize(text)
    vector = np.zeros(len(vocab))

    for word in tokens:
        if word in vocab:
            vector[vocab[word]] += 1

    return vector


def scratch_cosine_similarity(text1, text2):
    tokens1 = manual_tokenize(text1)
    tokens2 = manual_tokenize(text2)

    vocab = {word: i for i, word in enumerate(set(tokens1 + tokens2))}

    v1 = scratch_text_vectorize(text1, vocab)
    v2 = scratch_text_vectorize(text2, vocab)

    dot = np.dot(v1, v2)
    norm = np.linalg.norm(v1) * np.linalg.norm(v2)

    return dot / norm if norm != 0 else 0.0

# === BLOCK 2: Testing ===

spam_msgs = df[df['label']=='spam']['message'].head(3).tolist()
ham_msgs  = df[df['label']=='ham']['message'].head(3).tolist()

print("=== Scratch Similarity ===")

print("\nSpam vs Spam:")
print(scratch_cosine_similarity(spam_msgs[0], spam_msgs[1]))

print("\nSpam vs Ham:")
print(scratch_cosine_similarity(spam_msgs[0], ham_msgs[0]))

print("\nHam vs Ham:")
print(scratch_cosine_similarity(ham_msgs[0], ham_msgs[1]))

# === BLOCK 3: TF-IDF Similarity ===

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tfidf = TfidfVectorizer(
    max_features=3000,
    ngram_range=(1,2)   # 🔥 better context
)

tfidf_matrix = tfidf.fit_transform(df['message'].astype(str))

# === BLOCK 4: Query Similarity ===

query_idx = df[df['label']=='spam'].index[0]
query_vec = tfidf_matrix[query_idx]
query_text = df.loc[query_idx, 'message']

sim_scores = cosine_similarity(query_vec, tfidf_matrix).flatten()

# Top 5 similar messages
top_idx = sim_scores.argsort()[::-1][:5]

print("\nQuery Message:")
print(query_text[:80])

print("\nTop 5 Similar Messages:")

for i in top_idx:
    print(f"\n[{df.loc[i,'label'].upper()}] Score: {sim_scores[i]:.4f}")
    print(df.loc[i,'message'][:80])

# === BLOCK 5: Spam vs Ham Similarity ===

import numpy as np

spam_idx = np.where(df['label']=='spam')[0][:20]
ham_idx  = np.where(df['label']=='ham')[0][:20]

spam_vec = tfidf_matrix[spam_idx]
ham_vec  = tfidf_matrix[ham_idx]

spam_spam_sim = cosine_similarity(spam_vec, spam_vec).mean()
spam_ham_sim  = cosine_similarity(spam_vec, ham_vec).mean()

print("\nAverage Similarities:")
print(f"Spam vs Spam : {spam_spam_sim:.4f}")
print(f"Spam vs Ham  : {spam_ham_sim:.4f}")

# === BLOCK 6: Detect Similar Spam Messages ===

threshold = 0.8

similar_pairs = []

for i in spam_idx:
    for j in spam_idx:
        if i < j:
            sim = cosine_similarity(tfidf_matrix[i], tfidf_matrix[j])[0][0]
            if sim > threshold:
                similar_pairs.append((i, j, sim))

print("\nHighly Similar Spam Messages (>0.8):")

for i, j, sim in similar_pairs[:5]:
    print(f"\nSimilarity: {sim:.4f}")
    print("Msg1:", df.loc[i,'message'][:60])
    print("Msg2:", df.loc[j,'message'][:60])

"""#Classification Models"""

# === BLOCK 1: Improved Manual Naive Bayes ===

import math
from collections import defaultdict

class ManualNaiveBayes:

    def __init__(self):
        self.class_probs = {}                    # P(class)
        self.word_probs = defaultdict(dict)     # P(word|class)
        self.vocab = set()
        self.classes = []

    def fit(self, X_train, y_train):

        self.classes = list(set(y_train))
        total_docs = len(y_train)

        # group documents by class
        class_docs = {cls: [] for cls in self.classes}
        for text, label in zip(X_train, y_train):
            class_docs[label].append(text)

        # prior probabilities P(class)
        for cls in self.classes:
            self.class_probs[cls] = len(class_docs[cls]) / total_docs

        # build vocabulary
        for text in X_train:
            for word in text.split():
                self.vocab.add(word)

        vocab_size = len(self.vocab)

        # likelihood P(word|class)
        for cls in self.classes:
            word_counts = defaultdict(int)
            total_words = 0

            for text in class_docs[cls]:
                for word in text.split():
                    word_counts[word] += 1
                    total_words += 1

            for word in self.vocab:
                count = word_counts[word]
                self.word_probs[cls][word] = (count + 1) / (total_words + vocab_size)

def predict_single(self, text):
        words = text.split()

        scores = {}

        for cls in self.classes:
            score = math.log(self.class_probs[cls])

            for word in words:
                if word in self.vocab:
                    score += math.log(self.word_probs[cls][word])

            scores[cls] = score

        return max(scores, key=scores.get)


    def predict(self, X_test):
        return [self.predict_single(text) for text in X_test]

# === BLOCK 3: Training ===

print("Training Manual Naive Bayes...")

X_train_list = X_train.tolist()
X_test_list  = X_test.tolist()
y_train_list = y_train.tolist()
y_test_list  = y_test.tolist()

mnb = ManualNaiveBayes()
mnb.fit(X_train_list, y_train_list)

print("✅ Training complete")
print("Vocabulary size:", len(mnb.vocab))
print("Class probabilities:", mnb.class_probs)

import math
from collections import defaultdict

class ManualNaiveBayes:

    def __init__(self):
        self.class_probs = {}
        self.word_probs = defaultdict(dict)
        self.vocab = set()
        self.classes = []

    def fit(self, X_train, y_train):

        self.classes = list(set(y_train))
        total_docs = len(y_train)

        class_docs = {cls: [] for cls in self.classes}
        for text, label in zip(X_train, y_train):
            class_docs[label].append(text)

        # Prior probabilities
        for cls in self.classes:
            self.class_probs[cls] = len(class_docs[cls]) / total_docs

        # Vocabulary
        for text in X_train:
            for word in text.split():
                self.vocab.add(word)

        vocab_size = len(self.vocab)

        # Likelihood
        for cls in self.classes:
            word_counts = defaultdict(int)
            total_words = 0

            for text in class_docs[cls]:
                for word in text.split():
                    word_counts[word] += 1
                    total_words += 1

            for word in self.vocab:
                self.word_probs[cls][word] = (word_counts[word] + 1) / (total_words + vocab_size)

    # ✅ MUST be inside class
    def predict_single(self, text):
        words = text.split()
        score_dict = {}

        for cls in self.classes:
            score = math.log(self.class_probs[cls])

            for word in words:
                if word in self.vocab:
                    score += math.log(self.word_probs[cls][word])

            score_dict[cls] = score

        return max(score_dict, key=score_dict.get)

    # ✅ MUST be inside class
    def predict(self, X_test):
        return [self.predict_single(text) for text in X_test]

mnb = ManualNaiveBayes()
mnb.fit(X_train_list, y_train_list)

# === BLOCK 4: Evaluation ===

from sklearn.metrics import accuracy_score, f1_score, classification_report

print("\nPredicting...")

y_pred_manual = mnb.predict(X_test_list)

acc = accuracy_score(y_test_list, y_pred_manual)
f1  = f1_score(y_test_list, y_pred_manual)

print("\nManual Naive Bayes Results:")
print(f"Accuracy : {acc:.4f}")
print(f"F1 Score : {f1:.4f}")

print("\nClassification Report:")
print(classification_report(y_test_list, y_pred_manual, target_names=['Ham', 'Spam']))

# === BLOCK 5: Top Spam Words ===

spam_probs = mnb.word_probs[1]

# sort words by probability in spam class
top_spam_words = sorted(spam_probs.items(), key=lambda x: x[1], reverse=True)[:15]

print("\n🔥 Top Words Associated with Spam:")
for word, prob in top_spam_words:
    print(f"{word:<15} {prob:.6f}")

"""#  Classification Models - WITH LIBRARIES"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

models = {
    'Naive Bayes'        : MultinomialNB(),
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Linear SVM'         : LinearSVC(random_state=42, max_iter=1000)
}

vectorizers = {
    'CountVectorizer': (X_train_cv, X_test_cv),
    'TF-IDF'         : (X_train_tfidf, X_test_tfidf)
}

results = []

print("Training models...")
print("=" * 60)

for vec_name, (X_tr, X_te) in vectorizers.items():
    print(f"\nVectorizer: {vec_name}")
    print("-" * 40)

    for model_name, model in models.items():

        model.fit(X_tr, y_train)
        y_pred = model.predict(X_te)

        acc = accuracy_score(y_test, y_pred)
        f1  = f1_score(y_test, y_pred)

        print(f"{model_name:<25} | Acc: {acc:.4f} | F1: {f1:.4f}")

        results.append({
            'Model'     : model_name,
            'Vectorizer': vec_name,
            'Accuracy'  : acc,
            'F1 Score'  : f1
        })

results_df = pd.DataFrame(results)

# Find best model
best_row = results_df.loc[results_df['F1 Score'].idxmax()]

print("\n🔥 Best Model:")
print(best_row)

print("\nSummary Table:")
print(results_df)

# Bar plot comparison

plt.figure(figsize=(10,5))

for vec in results_df['Vectorizer'].unique():
    subset = results_df[results_df['Vectorizer'] == vec]
    plt.bar(subset['Model'] + " (" + vec + ")", subset['F1 Score'])

plt.xticks(rotation=30)
plt.title("Model Comparison (F1 Score)")
plt.ylabel("F1 Score")
plt.show()

# Train best model again

best_model_name = best_row['Model']
best_vectorizer = best_row['Vectorizer']

model = models[best_model_name]

if best_vectorizer == 'TF-IDF':
    X_tr, X_te = X_train_tfidf, X_test_tfidf
else:
    X_tr, X_te = X_train_cv, X_test_cv

model.fit(X_tr, y_train)
y_pred = model.predict(X_te)

print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Ham', 'Spam']))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(4,4))
sns.heatmap(cm, annot=True, fmt='d')

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""#Sentiment Analysis"""

#  Sentiment Analysis - All approaches on spam dataset
# checking if spam messages have different sentiment patterns than ham
# spam often uses overly positive/excited language to lure people

# -----------------------------------------------------------------------
# APPROACH 1:  (no libraries)
# -----------------------------------------------------------------------
# rule-based sentiment using positive and negative word lists
# score > 0 = positive, score < 0 = negative, score = 0 = neutral

positive_words = {
    'free', 'win', 'won', 'winner', 'cash', 'prize', 'great', 'good',
    'love', 'happy', 'congratulations', 'congrats', 'excellent', 'best',
    'amazing', 'fantastic', 'offer', 'bonus', 'reward', 'gift', 'lucky'
}

negative_words = {
    'fail', 'bad', 'terrible', 'awful', 'hate', 'worst', 'disappointed',
    'problem', 'issue', 'sorry', 'wrong', 'error', 'cancel', 'stop',
    'urgent', 'warning', 'expired', 'missed', 'lose', 'lost'
}

def scratch_sentiment(text):
    tokens = manual_tokenize(text)
    score  = 0
    for word in tokens:
        if word in positive_words:
            score += 1
        elif word in negative_words:
            score -= 1

    if score > 0:
        label = 'POSITIVE'
    elif score < 0:
        label = 'NEGATIVE'
    else:
        label = 'NEUTRAL'
    return score, label

print("=== FROM SCRATCH Sentiment ===")
spam_msgs = df[df['label'] == 'spam']['message'].head(3).tolist()
ham_msgs  = df[df['label'] == 'ham']['message'].head(3).tolist()

print("\nSpam messages:")
for msg in spam_msgs:
    score, label = scratch_sentiment(msg)
    print(f"  [{label}] score={score} | {msg[:70]}")

print("\nHam messages:")
for msg in ham_msgs:
    score, label = scratch_sentiment(msg)
    print(f"  [{label}] score={score} | {msg[:70]}")

# overall sentiment distribution on full dataset
df['scratch_sentiment'] = df['message'].apply(
    lambda x: scratch_sentiment(str(x))[1]
)
print("\nScratch Sentiment Distribution:")
print(df.groupby(['label', 'scratch_sentiment']).size().unstack(fill_value=0))

# -----------------------------------------------------------------------
# APPROACH 2: WITH LIBRARY (VADER - nltk)
# -----------------------------------------------------------------------
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon', quiet=True)

vader = SentimentIntensityAnalyzer()

def vader_sentiment(text):
    scores   = vader.polarity_scores(str(text))
    compound = scores['compound']
    if compound >= 0.05:
        label = 'POSITIVE'
    elif compound <= -0.05:
        label = 'NEGATIVE'
    else:
        label = 'NEUTRAL'
    return compound, label

print("\n=== WITH LIBRARY (VADER) Sentiment ===")
print("\nSpam messages:")
for msg in spam_msgs:
    score, label = vader_sentiment(msg)
    print(f"  [{label}] compound={score:.4f} | {msg[:70]}")

print("\nHam messages:")
for msg in ham_msgs:
    score, label = vader_sentiment(msg)
    print(f"  [{label}] compound={score:.4f} | {msg[:70]}")

# overall vader sentiment distribution
df['vader_sentiment'] = df['message'].apply(
    lambda x: vader_sentiment(str(x))[1]
)
print("\nVADER Sentiment Distribution:")
print(df.groupby(['label', 'vader_sentiment']).size().unstack(fill_value=0))

# comparison: scratch vs vader
print("\nComparison - Scratch vs VADER on spam messages:")
print(f"{'Message':<45} {'Scratch':<12} {'VADER'}")
print("-" * 70)
for msg in spam_msgs:
    _, s_label = scratch_sentiment(msg)
    _, v_label = vader_sentiment(msg)
    print(f"{msg[:43]:<45} {s_label:<12} {v_label}")

# cleanup temp columns
df.drop(columns=['scratch_sentiment', 'vader_sentiment'], inplace=True)

# Apply scratch sentiment
df['scratch_sentiment'] = df['message'].apply(scratch_sentiment)

print("\nScratch Sentiment Distribution:")
print(df.groupby(['label', 'scratch_sentiment']).size().unstack(fill_value=0))

# === BLOCK 3: VADER Sentiment ===

from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk

nltk.download('vader_lexicon', quiet=True)

vader = SentimentIntensityAnalyzer()

def vader_sentiment(text):
    score = vader.polarity_scores(str(text))['compound']

    if score >= 0.05:
        return 'POSITIVE'
    elif score <= -0.05:
        return 'NEGATIVE'
    else:
        return 'NEUTRAL'

df['vader_sentiment'] = df['message'].apply(vader_sentiment)

print("\nVADER Sentiment Distribution:")
print(df.groupby(['label', 'vader_sentiment']).size().unstack(fill_value=0))

import matplotlib.pyplot as plt

# Scratch sentiment plot
df.groupby(['label','scratch_sentiment']).size().unstack().plot(kind='bar', figsize=(8,5))
plt.title("Scratch Sentiment Distribution")
plt.ylabel("Count")
plt.show()

# VADER sentiment plot
df.groupby(['label','vader_sentiment']).size().unstack().plot(kind='bar', figsize=(8,5))
plt.title("VADER Sentiment Distribution")
plt.ylabel("Count")
plt.show()

def vader_sentiment(text):
    scores = vader.polarity_scores(str(text))
    compound = scores['compound']

    if compound >= 0.05:
        return 'POSITIVE'
    elif compound <= -0.05:
        return 'NEGATIVE'
    else:
        return 'NEUTRAL'

print(type(vader_sentiment(msg)))

"""#Deep Learning Model - Dense Neural Network"""

# Convert sparse → dense safely
X_train_dl = X_train_tfidf.astype('float32').toarray()
X_test_dl  = X_test_tfidf.astype('float32').toarray()

y_train_dl = y_train.values
y_test_dl  = y_test.values

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

model_dl = Sequential([
    Dense(256, activation='relu', input_shape=(X_train_dl.shape[1],)),
    BatchNormalization(),
    Dropout(0.4),

    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation='relu'),
    Dropout(0.2),

    Dense(1, activation='sigmoid')
])

import numpy as np

# Find indices
spam_indices = np.where(y_train_dl == 1)[0]
ham_indices  = np.where(y_train_dl == 0)[0]

# Oversample spam class
spam_oversampled = np.tile(spam_indices, len(ham_indices) // len(spam_indices) + 1)
spam_oversampled = spam_oversampled[:len(ham_indices)]

# Combine
all_indices = np.concatenate([ham_indices, spam_oversampled])

# Shuffle
np.random.seed(42)
np.random.shuffle(all_indices)

# Final balanced dataset
X_train_balanced = X_train_dl[all_indices]
y_train_balanced = y_train_dl[all_indices]

print("✅ Balanced dataset created")
print("Shape:", X_train_balanced.shape)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',   # track validation loss
    patience=3,           # stop after 3 epochs of no improvement
    restore_best_weights=True
)

model_dl.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model_dl.fit(
    X_train_balanced, y_train_balanced,
    epochs=20,
    batch_size=64,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)

import matplotlib.pyplot as plt

# Accuracy
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(['Train', 'Validation'])
plt.show()

# Loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend(['Train', 'Validation'])
plt.show()

y_pred_prob = model_dl.predict(X_test_dl, verbose=0)

# Try slightly stricter threshold (optional improvement)
y_pred_dl = (y_pred_prob >= 0.5).astype(int).flatten()

from sklearn.metrics import confusion_matrix

dl_acc = accuracy_score(y_test_dl, y_pred_dl)
dl_f1  = f1_score(y_test_dl, y_pred_dl)

print("\nDeep Learning Results:")
print(f"Accuracy : {dl_acc:.4f}")
print(f"F1 Score : {dl_f1:.4f}")

print("\nClassification Report:")
print(classification_report(y_test_dl, y_pred_dl, target_names=['Ham', 'Spam']))

from sklearn.metrics import confusion_matrix

dl_acc = accuracy_score(y_test_dl, y_pred_dl)
dl_f1  = f1_score(y_test_dl, y_pred_dl)

print("\nDeep Learning Results:")
print(f"Accuracy : {dl_acc:.4f}")
print(f"F1 Score : {dl_f1:.4f}")

print("\nClassification Report:")
print(classification_report(y_test_dl, y_pred_dl, target_names=['Ham', 'Spam']))

"""#  Confusion Matrix for all models"""

y_test_list = y_test.tolist()
y_test_dl_list = y_test_dl.tolist()

# Manual NB
y_pred_manual_nb = mnb.predict(X_test.tolist())

# Sklearn NB
nb_model = MultinomialNB()
nb_model.fit(X_train_cv, y_train)
y_pred_nb_cv = nb_model.predict(X_test_cv)

# Logistic Regression
lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train_cv, y_train)
y_pred_lr_cv = lr_model.predict(X_test_cv)

# SVM
svm_model_cv = LinearSVC(random_state=42, max_iter=1000)
svm_model_cv.fit(X_train_cv, y_train)
y_pred_svm_cv = svm_model_cv.predict(X_test_cv)

# Deep Learning
y_pred_prob_dl = model_dl.predict(X_test_dl, verbose=0)
y_pred_dl_final = (y_pred_prob_dl >= 0.5).astype(int).flatten()

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()

predictions = [
    (y_pred_manual_nb,  y_test_list,    'Manual Naive Bayes'),
    (y_pred_nb_cv,      y_test_list,    'Naive Bayes (CV)'),
    (y_pred_lr_cv,      y_test_list,    'Logistic Regression'),
    (y_pred_svm_cv,     y_test_list,    'Linear SVM'),
    (y_pred_dl_final,   y_test_dl_list, 'Deep Learning'),
]

for i, (y_pred, y_true, title) in enumerate(predictions):

    cm = confusion_matrix(y_true, y_pred)
    acc = accuracy_score(y_true, y_pred)

    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        ax=axes[i],
        xticklabels=['Ham', 'Spam'],
        yticklabels=['Ham', 'Spam']
    )

    axes[i].set_title(f"{title}\nAccuracy: {acc:.4f}")
    axes[i].set_xlabel('Predicted')
    axes[i].set_ylabel('Actual')

# Hide empty subplot
axes[5].set_visible(False)

plt.suptitle('Confusion Matrices - All Models', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

# Use results from previous models instead of hardcoding
results_df = pd.DataFrame(results)

# convert to percentage
results_df['Accuracy'] = (results_df['Accuracy'] * 100).round(2)
results_df['F1 Score'] = (results_df['F1 Score'] * 100).round(2)

labels = results_df.apply(
    lambda r: f"{r['Model']}\n({r['Vectorizer']})", axis=1
)

accuracies = results_df['Accuracy'].values
f1_scores  = results_df['F1 Score'].values

x = np.arange(len(labels))
width = 0.35

fig, ax = plt.subplots(figsize=(14, 6))

bars1 = ax.bar(x - width/2, accuracies, width, label='Accuracy (%)')
bars2 = ax.bar(x + width/2, f1_scores,  width, label='F1 Score (%)')

ax.set_title('Model Comparison - Accuracy & F1 Score')
ax.set_xticks(x)
ax.set_xticklabels(labels, fontsize=8)
ax.set_ylim(85, 100)
ax.legend()

plt.tight_layout()
plt.show()

for bar in bars1:
    axes[0].text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 0.1,
                 f'{bar.get_height():.1f}',
                 ha='center', fontsize=7)

for bar in bars2:
    axes[0].text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + 0.1,
                 f'{bar.get_height():.1f}',
                 ha='center', fontsize=7)

axes[1].axis('off')

table_data = results_df[['Model','Vectorizer','Accuracy','F1 Score']].values

table = axes[1].table(
    cellText=table_data,
    colLabels=['Model','Vectorizer','Accuracy','F1 Score'],
    cellLoc='center',
    loc='center'
)

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 1.8)

# ✅ find best model dynamically
best_idx = results_df['F1 Score'].idxmax()

for j in range(4):
    table[best_idx + 1, j].set_facecolor('#d4edda')  # +1 because header row

axes[1].set_title('Summary Table (Best Model Highlighted)', pad=20)

plt.tight_layout()
plt.show()

print("\nFinal Results:")
print(results_df.to_string(index=False))

